version: '3'

services:
  hasura:
    container_name: hasura
    image: hasura
    build:
      context: ./hasura
    depends_on:
      db:
        condition: service_healthy
    env_file: ./hasura/.env
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    ports:
      - '8080:8080'

  db:
    container_name: db
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./hasura/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --dbname=database --username=user']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    image: app
    build:
      context: .
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/hasura

volumes:
  db_data:
